# Generated by Django 4.0.3 on 2022-03-30 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, default='', max_length=50)),
                ('Course_Number', models.IntegerField(blank=True, default='', max_length=20)),
                ('Instructor_Name', models.CharField(blank=True, default='', max_length=50)),
                ('Duration', models.FloatField(default=0.0)),
            ],
        ),
    ]
